### ISSUE TITLE
Feature Request: Opt-out feature

### ISSUE THREAD

**Issue by michaelvcolianna** [jycouet/jyc.dev#10]
It would be nice to have a way to opt-out of your data being used like the "BlueSkyRoast" app had. Alternatively, if this is opt-in only, a notice stating that would be great. Thanks!

(I didn't see an issue template, apologies if this should have been in a particular format.)

**Comment by jycouet** [comment]
Hi @michaelvcolianna, no worries, there is no specific template 👍

I really started to be on bsky like 2 months ago and discovered this ATProtocol just after. And the eye opener was https://atproto-browser.vercel.app for me. It's like a second internet where different app can look at the same data and do different things.
- https://atproto-browser.vercel.app => Browsing raw data
- https://pdsls.dev => Browsing raw data (and some edit now!)
- https://bsky.app => Interacting with others (the main one today ^^)
- https://whtwnd.com => Bloging
- ... and many many more
- https://skyzoo.blue  => display statistics
- ... and many many more

If I read between lines of your `opt-out` | `opt-in` request, you would like your data to not be "used" in skyzoo ? By anyone ? The thing is that all data displayed are public (and even, as you saw, all my code is Open Source!), so I'm not sure what to do. Anyone can go and fetch all these data directly in the ATProtocol.
As you can see also, I'm not sending ATProto data to an LLM or whatever, and I'm just displaying an Animal based on an hand crafted algo. Trying to get some positive vibes around this new (to me) social media 🌈.

Additionally, it can help some people to find out bot behavior under some handle.

Also, I like to see skyzoo really showing that all ATProto data is public, and anyone can scan the full network.

Let me know your thoughts.

**Comment by jycouet** [comment]
Thinking a bit more, I could maintain an `opt-out` list, if people contact me _(at https://bsky.app/profile/skyzoo.blue)_, I can remove them from being seen in Skyzoo.

What do you think about this ?

**Comment by jycouet** [comment]
Update, I just did this: https://bsky.app/profile/did:plc:dacfxuonkf2qtqft22sc23tu/post/3lcso6q23d224
What do you think?

**Comment by michaelvcolianna** [comment]
Looks good, thanks! Mainly I was concerned because the other app I mentioned was using generative AI, which you've explicitly indicated isn't the case. (You may want to tout that, we hate gen AI on bsky!)

Also I saw that one user was able to see they forgot some ALT text on their images, so it looks like your app is pretty helpful. ☺️

**Comment by jycouet** [comment]
Thank you for the feedback. 
Yes, you get an `Epic` title when you have alt text. My hope is that with gamification, we educate people about good practices ;)

Take care 👍
